### ISSUE TITLE
Adding recaptcha is not working

### ISSUE THREAD

**Issue by usuenapal** [PrestaCraft/custompopup#21]
I'm trying to add recaptcha v2 as a widget on the pop up.

```
<html>
  <head>
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
  </head>
  <body>
    <form action="" method="POST">
      <div class="g-recaptcha" data-sitekey="your_site_key"></div>
      <br/>
      <input type="submit" value="Submit">
    </form>
  </body>
</html> 
```

I add the form code on the pop up content but the recpatcha is not being rendered. I have a delay of 15 seconds on home section.

Thanks in advance!

**Comment by elektryz** [comment]
Hi

Where do you try to put this code?
If you try to put this into TinyMCE content field in module configuration page - it may not work (because it may cut some HTML tags etc.)

https://github.com/PrestaCraft/custompopup/blob/master/views/templates/hook/custompopup.tpl#L51
Whole, generated popup content is located here (line 51). 
I'd suggest adding your form here, but move the script to the header or footer of your template.

If it will work with Tingle.js (the popup used by module) it should also work with custompopup module.

**Comment by usuenapal** [comment]
Hi! I'm editing but the update in not being reflected on the web. :/

I'm editing the file /public_html/modules/custompopup/views/templates/hook/custompopup.tpl

To test, I delete the line `modal.setContent(content); `

but the content continue appearing. Cache, browser data and all deleted....
